---
title: "Visualization"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)

library(p8105.datasets)
data("weather_df")
```

Now we have everything we need.

```{r}
weather_df
```

Let's make a scatterplot!

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()
```

```{r}
ggp_temp_scatterplot = 
  weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

ggp_temp_scatterplot
```

Let's make this a bit fancier.

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .25) +
  geom_smooth(se = FALSE)
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point(aes(color = name), alpha = .25) +
  geom_smooth(se = FALSE)
```

Aesthetics are up to you.

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_smooth(se = FALSE)
```

Show faceting

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point (alpha = .5) +
  facet_grid(. ~ name)
```

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax, color = name)) +
  geom_point (alpha = .5) +
  facet_grid(cols = vars(name))
```

Let's look at something else.

```{r}
weather_df |>
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~ name)
```

Make a plot of Central Park tmax vs tmin only, and convert temperatures to fahrenheit.

```{r}
weather_df |>
  filter(name == "CentralPark_NY") |>
  mutate(
    tmax = tmax * (9 / 5) + 32,
    tmin = tmin * (9 / 5) + 32
  ) |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```

What's a hex plot?

```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_hex()
```

## Univariate plots

```{r}
weather_df |> 
  ggplot(aes(x = tmax)) +
  geom_histogram()
```

```{r}
weather_df |> 
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram() +
  facet_grid (. ~ name)
```

Density plots

```{r}
weather_df |> 
  ggplot(aes(x = tmax, fill = name)) +
  geom_density(alpha = .3)
```

Box plots

```{r}
weather_df |> 
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()
```

Violin plots

```{r}
weather_df |> 
  ggplot(aes(x = name, y = tmax)) +
  geom_violin()
```

Ridge plots

```{r}
weather_df |> 
  ggplot(aes(x = tmax, y = name)) +
  geom_density_ridges()
```

## Save some of my plots

```{r}
ggp_weather = 
  weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) +
  geom_point(aes(size = prcp), alpha = .5) +
  facet_grid(. ~ name)

ggsave("plots/ggp_weather.pdf", ggp_weather)
```

```{r, fig.width = 12, fig.height = 12}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```

